// generated 2011/7/7 21:51:53 CEST by christof@christof-hp.(none)
// using glademm V2.13.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- --gnome2 tree.glade
// for gtk 2.24.4 and gtkmm 2.24.0
//
// Please modify the corresponding derived classes in .//simplest.hh and.//simplest.cc

#ifndef _SIMPLEST_GLADE_HH
#  define _SIMPLEST_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include "SimpleTree.hh"

class simplest_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
protected:
        class SimpleTree * treebase;
        
        simplest_glade();
        
        ~simplest_glade();
private:
        virtual void on_Beenden_activate() = 0;
};
#endif
