// generated 2004/5/4 10:01:51 CEST by christof@puck.petig-baender.de
// using glademm V2.5.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- --gnome2 tree.glade
// for gtk 2.4.0 and gtkmm 2.4.0
//
// Please modify the corresponding derived classes in .//simplest.hh and.//simplest.cc

#ifndef _SIMPLEST_GLADE_HH
#  define _SIMPLEST_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include "SimpleTree.hh"

class simplest_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
protected:
        class SimpleTree *treebase;
        
        simplest_glade();
        
        ~simplest_glade();
private:
        virtual void on_Beenden_activate() = 0;
};
#endif
