// generated 2011/7/7 21:48:08 CEST by christof@christof-hp.(none)
// using glademm V2.13.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- tree.glade
// for gtk 0.0.0 and gtkmm 0.0.0
//
// Please modify the corresponding derived classes in .//simplest.cc

#include "config.h"
#include "simplest_glade.hh"
#include <gtk--/menuitem.h>
#include <gtk--/menu.h>
#include <gtk--/menubar.h>
#include <gtk--/box.h>

simplest_glade::simplest_glade(
) : Gtk_Window(GTK_WINDOW_TOPLEVEL)
{  
   
   Gtk_Window *simplest = this;
   Gtk_MenuItem *Beenden = NULL;
   Gtk_Menu *menu1 = manage(new class Gtk_Menu());
   Gtk_MenuItem *Datei = NULL;
   Gtk_MenuBar *menubar1 = manage(new class Gtk_MenuBar());
   treebase = new class SimpleTree(5);
   
   Gtk_VBox *vbox1 = manage(new class Gtk_VBox(false, 0));
   
   menu1->items().push_back(Gtk::Menu_Helpers::MenuElem(""));
   Beenden = (Gtk_MenuItem *)menu1->items().back();
   
   menubar1->items().push_back(Gtk::Menu_Helpers::MenuElem("", *menu1));
   Datei = (Gtk_MenuItem *)menubar1->items().back();
   menubar1->set_shadow_type(GTK_SHADOW_OUT);
   vbox1->pack_start(*menubar1, false, true, 0);
   vbox1->pack_start(*treebase);
   simplest->set_title("");
   simplest->set_position(GTK_WIN_POS_NONE);
   simplest->set_policy(true, true, false);
   simplest->add(*vbox1);
   Beenden->show();
   menu1->show();
   Datei->show();
   menubar1->show();
   treebase->show();
   vbox1->show();
   simplest->show();
   Beenden->activate.connect(sigc::mem_fun(this, &simplest_glade::on_Beenden_activate));
}

simplest_glade::~simplest_glade()
{  delete treebase;
}
