// generated 2011/7/7 21:48:08 CEST by christof@christof-hp.(none)
// using glademm V2.13.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- tree.glade
// for gtk 0.0.0 and gtkmm 0.0.0
//
// Please modify the corresponding derived classes in .//simplest.hh and.//simplest.cc

#ifndef _SIMPLEST_GLADE_HH
#  define _SIMPLEST_GLADE_HH

#include <gtk--/window.h>
#include "SimpleTree.hh"

class simplest_glade : public Gtk_Window
{  
protected:
        
        class SimpleTree * treebase;
        
        simplest_glade();
        
        ~simplest_glade();
private:
        virtual void on_Beenden_activate() = 0;
};
#endif
