// generated 2004/5/4 10:01:51 CEST by christof@puck.petig-baender.de
// using glademm V2.5.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- --gnome2 tree.glade
// for gtk 2.4.0 and gtkmm 2.4.0
//
// Please modify the corresponding derived classes in .//simplest.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/compatibility.h>
#endif //gtkmm 2.3+
#include "simplest_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include <gtkmm/menuitem.h>
#include <gtkmm/menu.h>
#include <gtkmm/menubar.h>
#include <gtkmm/box.h>

simplest_glade::simplest_glade(
) : Gtk::Window(Gtk::WINDOW_TOPLEVEL)
{  
   
   Gtk::Window *simplest = this;
   gmm_data = new GlademmData(get_accel_group());
   
   Gtk::MenuItem *Beenden = NULL;
   Gtk::Menu *menu1 = Gtk::manage(new class Gtk::Menu());
   Gtk::MenuItem *Datei = NULL;
   Gtk::MenuBar *menubar1 = Gtk::manage(new class Gtk::MenuBar());
   treebase = new class SimpleTree(5);
   
   Gtk::VBox *vbox1 = Gtk::manage(new class Gtk::VBox(false, 0));
   
   menu1->items().push_back(Gtk::Menu_Helpers::MenuElem("Beenden"));
   Beenden = (Gtk::MenuItem *)&menu1->items().back();
   
   menubar1->items().push_back(Gtk::Menu_Helpers::MenuElem("Datei", *menu1));
   Datei = (Gtk::MenuItem *)&menubar1->items().back();
   vbox1->pack_start(*menubar1, Gtk::PACK_SHRINK, 0);
   vbox1->pack_start(*treebase);
   simplest->set_title("simplest");
   simplest->set_modal(false);
   simplest->set_position(Gtk::WIN_POS_NONE);
   simplest->property_allow_shrink().set_value(true);
   simplest->property_allow_grow().set_value(true);
   simplest->add(*vbox1);
   Beenden->show();
   menu1->show();
   Datei->show();
   menubar1->show();
   treebase->show();
   vbox1->show();
   simplest->show();
   Beenden->signal_activate().connect(SigC::slot(*this, &simplest_glade::on_Beenden_activate));
}

simplest_glade::~simplest_glade()
{  delete treebase;
   delete gmm_data;
}
