// generated 2011/7/7 21:48:08 CEST by christof@christof-hp.(none)
// using glademm V2.13.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- tree.glade
// for gtk 0.0.0 and gtkmm 0.0.0
//
// Please modify the corresponding derived classes in .//with_class.cc

#include "config.h"
#include "with_class_glade.hh"
#include <gtk--/menuitem.h>
#include <gtk--/menu.h>
#include <gtk--/menubar.h>
#include <gtk--/scrolledwindow.h>
#include <gtk--/box.h>

with_class_glade::with_class_glade(
) : Gtk_Window(GTK_WINDOW_TOPLEVEL)
{  
   
   Gtk_Window *with_class = this;
   Gtk_MenuItem *menuitem2 = NULL;
   Gtk_Menu *menu2 = manage(new class Gtk_Menu());
   Gtk_MenuItem *menuitem1 = NULL;
   Gtk_MenuBar *menubar2 = manage(new class Gtk_MenuBar());
   treebase = new class SimpleTree(6);
   
   Gtk_ScrolledWindow *scrolledwindow1 = manage(new class Gtk_ScrolledWindow());
   Gtk_VBox *vbox2 = manage(new class Gtk_VBox(false, 0));
   
   menu2->items().push_back(Gtk::Menu_Helpers::MenuElem(""));
   menuitem2 = (Gtk_MenuItem *)menu2->items().back();
   
   menubar2->items().push_back(Gtk::Menu_Helpers::MenuElem("", *menu2));
   menuitem1 = (Gtk_MenuItem *)menubar2->items().back();
   menubar2->set_shadow_type(GTK_SHADOW_OUT);
   scrolledwindow1->set_policy(GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
   scrolledwindow1->add(*treebase);
   vbox2->pack_start(*menubar2, false, true, 0);
   vbox2->pack_start(*scrolledwindow1);
   with_class->set_title("");
   with_class->set_default_size(500,200);
   with_class->set_position(GTK_WIN_POS_NONE);
   with_class->set_policy(true, true, false);
   with_class->add(*vbox2);
   menuitem2->show();
   menu2->show();
   menuitem1->show();
   menubar2->show();
   treebase->show();
   scrolledwindow1->show();
   vbox2->show();
   with_class->show();
   menuitem2->activate.connect(sigc::mem_fun(this, &with_class_glade::on_Beenden_activate));
}

with_class_glade::~with_class_glade()
{  delete treebase;
}
