// generated 2011/7/7 21:51:53 CEST by christof@christof-hp.(none)
// using glademm V2.13.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- --gnome2 tree.glade
// for gtk 2.24.4 and gtkmm 2.24.0
//
// Please modify the corresponding derived classes in .//with_class.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/bind.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "with_class_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include <gtkmm/menuitem.h>
#include <gtkmm/menu.h>
#include <gtkmm/menubar.h>
#include <gtkmm/scrolledwindow.h>
#include <gtkmm/box.h>

with_class_glade::with_class_glade(
) : Gtk::Window(Gtk::WINDOW_TOPLEVEL)
{  
   
   Gtk::Window *with_class = this;
   gmm_data = new GlademmData(get_accel_group());
   
   Gtk::MenuItem *menuitem2 = NULL;
   Gtk::Menu *menu2 = Gtk::manage(new class Gtk::Menu());
   Gtk::MenuItem *menuitem1 = NULL;
   Gtk::MenuBar *menubar2 = Gtk::manage(new class Gtk::MenuBar());
   treebase = new class SimpleTree(6);
   
   Gtk::ScrolledWindow *scrolledwindow1 = Gtk::manage(new class Gtk::ScrolledWindow());
   Gtk::VBox *vbox2 = Gtk::manage(new class Gtk::VBox(false, 0));
   
   menu2->items().push_back(Gtk::Menu_Helpers::MenuElem(""));
   menuitem2 = (Gtk::MenuItem *)&menu2->items().back();
   
   menubar2->items().push_back(Gtk::Menu_Helpers::MenuElem("", *menu2));
   menuitem1 = (Gtk::MenuItem *)&menubar2->items().back();
   scrolledwindow1->set_shadow_type(Gtk::SHADOW_NONE);
   scrolledwindow1->set_policy(Gtk::POLICY_AUTOMATIC, Gtk::POLICY_AUTOMATIC);
   scrolledwindow1->add(*treebase);
   vbox2->pack_start(*menubar2, Gtk::PACK_SHRINK, 0);
   vbox2->pack_start(*scrolledwindow1);
   with_class->set_title("");
   with_class->set_default_size(500,200);
   with_class->set_position(Gtk::WIN_POS_NONE);
   with_class->property_allow_shrink().set_value(true);
   with_class->add(*vbox2);
   menuitem2->show();
   menu2->show();
   menuitem1->show();
   menubar2->show();
   treebase->show();
   scrolledwindow1->show();
   vbox2->show();
   with_class->show();
   menuitem2->signal_activate().connect(sigc::mem_fun(*this, &with_class_glade::on_Beenden_activate), false);
}

with_class_glade::~with_class_glade()
{  delete treebase;
   delete gmm_data;
}
