// generated 2011/7/7 21:48:08 CEST by christof@christof-hp.(none)
// using glademm V2.13.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- tree.glade
// for gtk 0.0.0 and gtkmm 0.0.0
//
// Please modify the corresponding derived classes in .//with_class.hh and.//with_class.cc

#ifndef _WITH_CLASS_GLADE_HH
#  define _WITH_CLASS_GLADE_HH

#include <gtk--/window.h>
#include "SimpleTree.hh"

class with_class_glade : public Gtk_Window
{  
protected:
        
        class SimpleTree * treebase;
        
        with_class_glade();
        
        ~with_class_glade();
private:
        virtual void on_Beenden_activate() = 0;
};
#endif
