// generated 2003/4/7 12:58:37 CEST by christof@puck.petig-baender.de
// using glademm V1.1.3g_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- --baseclass mvc.glade
// for gtk 2.2.1 and gtkmm 2.2.0
//
// Please modify the corresponding derived classes in ././window1.hh and././window1.cc

#ifndef _WINDOW1_GLADE_HH
#  define _WINDOW1_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include "int_SpinButton.hh"
#include "string_Entry.hh"
#include "bool_CheckButton.hh"
#include "bool_ImageButton.hh"
#include <gtkmm/label.h>
#include <gtkmm/spinbutton.h>
#include "./mvc_base.hh"

class window1_glade : public Gtk::Window, public window1_base
{  
        
        GlademmData *gmm_data;
        class int_SpinButton *intwidget;
protected:
        class string_Entry *stringwidget;
        class bool_CheckButton *boolwidget;
private:
        class bool_CheckButton *custom1;
        class bool_ImageButton *custom2;
protected:
        class Gtk::Label *label1;
        class Gtk::SpinButton *spinbutton1;
        
        window1_glade();
        
        ~window1_glade();
private:
        virtual void loeschen() = 0;
        virtual void randomize() = 0;
};
#endif
