// generated 2008/12/22 13:29:26 CET by christof@vesta.(none)
// using glademm V2.13.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- newtree.glade
// for gtk 2.14.5 and gtkmm 2.14.3
//
// Please modify the corresponding derived classes in ././window1.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/bind.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "window1_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include <gtkmm/image.h>
#include <gtkmm/label.h>
#include <gtkmm/box.h>
#include <gtkmm/alignment.h>
#include <gtkmm/button.h>
#include <gtkmm/buttonbox.h>

window1_glade::window1_glade(
) : Gtk::Window(Gtk::WINDOW_TOPLEVEL)
{  window1 = this;
   gmm_data = new GlademmData(get_accel_group());
   scrolledwindow1 = Gtk::manage(new class Gtk::ScrolledWindow());
   
   Gtk::Image *image1 = Gtk::manage(new class Gtk::Image(Gtk::StockID("gtk-add"), Gtk::IconSize(4)));
   Gtk::Label *label1 = Gtk::manage(new class Gtk::Label("Dazu"));
   Gtk::HBox *hbox1 = Gtk::manage(new class Gtk::HBox(false, 2));
   Gtk::Alignment *alignment1 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 0, 0));
   Gtk::Button *button1 = Gtk::manage(new class Gtk::Button());
   Gtk::Image *image4 = Gtk::manage(new class Gtk::Image(Gtk::StockID("gtk-delete"), Gtk::IconSize(4)));
   Gtk::Label *label4 = Gtk::manage(new class Gtk::Label("Weg"));
   Gtk::HBox *hbox4 = Gtk::manage(new class Gtk::HBox(false, 2));
   Gtk::Alignment *alignment4 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 0, 0));
   Gtk::Button *button2 = Gtk::manage(new class Gtk::Button());
   Gtk::Image *image3 = Gtk::manage(new class Gtk::Image(Gtk::StockID("gtk-refresh"), Gtk::IconSize(4)));
   Gtk::Label *label3 = Gtk::manage(new class Gtk::Label("refresh"));
   Gtk::HBox *hbox3 = Gtk::manage(new class Gtk::HBox(false, 2));
   Gtk::Alignment *alignment3 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 0, 0));
   Gtk::Button *button3 = Gtk::manage(new class Gtk::Button());
   Gtk::Image *image6 = Gtk::manage(new class Gtk::Image(Gtk::StockID("gtk-execute"), Gtk::IconSize(4)));
   Gtk::Label *label6 = Gtk::manage(new class Gtk::Label("viel ändern"));
   Gtk::HBox *hbox6 = Gtk::manage(new class Gtk::HBox(false, 2));
   Gtk::Alignment *alignment6 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 0, 0));
   Gtk::Button *button4 = Gtk::manage(new class Gtk::Button());
   Gtk::Image *image5 = Gtk::manage(new class Gtk::Image(Gtk::StockID("gtk-execute"), Gtk::IconSize(4)));
   Gtk::Label *label5 = Gtk::manage(new class Gtk::Label("wenig ändern"));
   Gtk::HBox *hbox5 = Gtk::manage(new class Gtk::HBox(false, 2));
   Gtk::Alignment *alignment5 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 0, 0));
   Gtk::Button *button5 = Gtk::manage(new class Gtk::Button());
   Gtk::Image *image7 = Gtk::manage(new class Gtk::Image(Gtk::StockID("gtk-dialog-question"), Gtk::IconSize(4)));
   Gtk::Label *label7 = Gtk::manage(new class Gtk::Label("Test"));
   Gtk::HBox *hbox7 = Gtk::manage(new class Gtk::HBox(false, 2));
   Gtk::Alignment *alignment7 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 0, 0));
   Gtk::Button *button_test = Gtk::manage(new class Gtk::Button());
   Gtk::HButtonBox *hbuttonbox1 = Gtk::manage(new class Gtk::HButtonBox(Gtk::BUTTONBOX_EDGE, 4));
   Gtk::VBox *vbox1 = Gtk::manage(new class Gtk::VBox(false, 0));
   scrolledwindow1->set_flags(Gtk::CAN_FOCUS);
   scrolledwindow1->set_shadow_type(Gtk::SHADOW_NONE);
   scrolledwindow1->set_policy(Gtk::POLICY_AUTOMATIC, Gtk::POLICY_AUTOMATIC);
   scrolledwindow1->property_window_placement().set_value(Gtk::CORNER_BOTTOM_RIGHT);
   hbox1->pack_start(*image1, Gtk::PACK_SHRINK, 0);
   hbox1->pack_start(*label1, Gtk::PACK_SHRINK, 0);
   alignment1->add(*hbox1);
   button1->set_flags(Gtk::CAN_FOCUS);
   button1->set_flags(Gtk::CAN_DEFAULT);
   button1->add(*alignment1);
   hbox4->pack_start(*image4, Gtk::PACK_SHRINK, 0);
   hbox4->pack_start(*label4, Gtk::PACK_SHRINK, 0);
   alignment4->add(*hbox4);
   button2->set_flags(Gtk::CAN_FOCUS);
   button2->set_flags(Gtk::CAN_DEFAULT);
   button2->set_relief(Gtk::RELIEF_HALF);
   button2->add(*alignment4);
   hbox3->pack_start(*image3, Gtk::PACK_SHRINK, 0);
   hbox3->pack_start(*label3, Gtk::PACK_SHRINK, 0);
   alignment3->add(*hbox3);
   button3->set_flags(Gtk::CAN_FOCUS);
   button3->set_flags(Gtk::CAN_DEFAULT);
   button3->add(*alignment3);
   hbox6->pack_start(*image6, Gtk::PACK_SHRINK, 0);
   hbox6->pack_start(*label6, Gtk::PACK_SHRINK, 0);
   alignment6->add(*hbox6);
   button4->set_flags(Gtk::CAN_FOCUS);
   button4->set_flags(Gtk::CAN_DEFAULT);
   button4->add(*alignment6);
   hbox5->pack_start(*image5, Gtk::PACK_SHRINK, 0);
   hbox5->pack_start(*label5, Gtk::PACK_SHRINK, 0);
   alignment5->add(*hbox5);
   button5->set_flags(Gtk::CAN_FOCUS);
   button5->set_flags(Gtk::CAN_DEFAULT);
   button5->add(*alignment5);
   hbox7->pack_start(*image7, Gtk::PACK_SHRINK, 0);
   hbox7->pack_start(*label7, Gtk::PACK_SHRINK, 0);
   alignment7->add(*hbox7);
   button_test->set_flags(Gtk::CAN_FOCUS);
   button_test->set_flags(Gtk::CAN_DEFAULT);
   button_test->add(*alignment7);
   hbuttonbox1->pack_start(*button1);
   hbuttonbox1->pack_start(*button2);
   hbuttonbox1->pack_start(*button3);
   hbuttonbox1->pack_start(*button4);
   hbuttonbox1->pack_start(*button5);
   hbuttonbox1->pack_start(*button_test);
   vbox1->pack_start(*scrolledwindow1);
   vbox1->pack_start(*hbuttonbox1, Gtk::PACK_SHRINK, 0);
   window1->set_title("window1");
   window1->set_default_size(600,400);
   window1->add(*vbox1);
   scrolledwindow1->show();
   image1->show();
   label1->show();
   hbox1->show();
   alignment1->show();
   button1->show();
   image4->show();
   label4->show();
   hbox4->show();
   alignment4->show();
   button2->show();
   image3->show();
   label3->show();
   hbox3->show();
   alignment3->show();
   button3->show();
   image6->show();
   label6->show();
   hbox6->show();
   alignment6->show();
   button4->show();
   image5->show();
   label5->show();
   hbox5->show();
   alignment5->show();
   button5->show();
   image7->show();
   label7->show();
   hbox7->show();
   alignment7->show();
   button_test->show();
   hbuttonbox1->show();
   vbox1->show();
   window1->show();
   button1->signal_clicked().connect(sigc::mem_fun(*this, &window1_glade::add_one), false);
   button2->signal_clicked().connect(sigc::mem_fun(*this, &window1_glade::eine_weg), false);
   button3->signal_clicked().connect(sigc::mem_fun(*this, &window1_glade::refresh), false);
   button4->signal_clicked().connect(sigc::mem_fun(*this, &window1_glade::change1), false);
   button5->signal_clicked().connect(sigc::mem_fun(*this, &window1_glade::change2), false);
   button_test->signal_clicked().connect(sigc::mem_fun(*this, &window1_glade::on_button_test_clicked), false);
}

window1_glade::~window1_glade()
{  delete gmm_data;
}
