// generated 2004/5/3 18:38:16 CEST by christof@puck.petig-baender.de
// using glademm V2.5.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- newtree.glade
// for gtk 2.4.0 and gtkmm 2.4.0
//
// Please modify the corresponding derived classes in ././window1.hh and././window1.cc

#ifndef _WINDOW1_GLADE_HH
#  define _WINDOW1_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include <gtkmm/scrolledwindow.h>

class window1_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
protected:
        class Gtk::Window *window1;
        class Gtk::ScrolledWindow *scrolledwindow1;
        
        window1_glade();
        
        ~window1_glade();
private:
        virtual void add_one() = 0;
        virtual void eine_weg() = 0;
        virtual void refresh() = 0;
        virtual void change1() = 0;
        virtual void change2() = 0;
};
#endif
