// generated 2005/12/1 17:53:18 CET by christof@vesta.petig-baender.de
// using glademm V2.10.0.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- dwhouse.glade
// for gtk 2.8.8 and gtkmm 2.8.1
//
// Please modify the corresponding derived classes in ././window1.hh and././window1.cc

#ifndef _WINDOW1_GLADE_HH
#  define _WINDOW1_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include "MyTreeBase.hh"
#include <gtkmm/box.h>

class window1_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
protected:
        class MyTreeBase * treebase;
        class Gtk::VBox * vbox1;
        
        window1_glade();
        
        ~window1_glade();
private:
        virtual void on_Beenden_activate() = 0;
        virtual void on_neuordnen_activate() = 0;
};
#endif
