// $Id: window1_glade.cc,v 1.2 2002/07/05 12:36:56 christof Exp $
/*  libKomponenten: GUI components for ManuProC's libcommon++
 *  Copyright (C) 2001 Adolf Petig GmbH & Co. KG, written by Jacek Jakubowski
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

// generated 2001/3/2 16:01:13 CET by jacek@mimi.
// using glademm V0.5_11f_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- dwhouse.glade
// for gtk 1.2.8 and gtkmm 1.2.5
//
// Please modify the corresponding derived classes in ./marc2/window1.cc

#include "config.h"
#include "window1.hh"
#include <gtk--/list.h>
#include <gtk--/menu.h>
#include <gtk--/menubar.h>

window1_glade::window1_glade(
) : Gtk::Window(GTK_WINDOW_TOPLEVEL)
{   
   
   Gtk::Window *window1 = this;
   Gtk::MenuItem *Beenden = manage(new class Gtk::MenuItem("Beenden"));
   Gtk::Menu *menu1 = manage(new class Gtk::Menu());
   Gtk::MenuItem *Datei = manage(new class Gtk::MenuItem("Datei"));
   Gtk::MenuBar *menubar1 = manage(new class Gtk::MenuBar());
   treebase = new class MyTreeBase(5, 3);
   vbox1 = manage(new class Gtk::VBox(false, 0));
   menu1->append(*Beenden);
   Datei->set_submenu(*menu1);
   menubar1->append(*Datei);
   vbox1->pack_start(*menubar1, false, true, 0);
   vbox1->pack_start(*treebase);
   window1->set_title("window1");
   window1->set_policy(true, true, false);
   window1->add(*vbox1);
   Beenden->show();
   menu1->show();
   Datei->show();
   menubar1->show();
   treebase->show();
   vbox1->show();
   window1->show();
   Beenden->activate.connect(SigC::slot(static_cast<class window1*>(this), &window1::on_Beenden_activate));
}

window1_glade::~window1_glade()
{   delete treebase;
}
