// generated 2005/12/1 17:53:18 CET by christof@vesta.petig-baender.de
// using glademm V2.10.0.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- dwhouse.glade
// for gtk 2.8.8 and gtkmm 2.8.1
//
// Please modify the corresponding derived classes in ././window1.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/compatibility.h>
#include <sigc++/bind.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "window1_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include <gtkmm/menuitem.h>
#include <gtkmm/menu.h>
#include <gtkmm/menubar.h>

window1_glade::window1_glade(
) : Gtk::Window(Gtk::WINDOW_TOPLEVEL)
{  
   
   Gtk::Window *window1 = this;
   gmm_data = new GlademmData(get_accel_group());
   
   Gtk::MenuItem *Beenden = NULL;
   Gtk::Menu *Datei_menu = Gtk::manage(new class Gtk::Menu());
   Gtk::MenuItem *Datei = NULL;
   Gtk::MenuItem *neuordnen = NULL;
   Gtk::MenuBar *menubar1 = Gtk::manage(new class Gtk::MenuBar());
   treebase = new class MyTreeBase(5);
   vbox1 = Gtk::manage(new class Gtk::VBox(false, 0));
   
   
   Datei_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("Beenden"));
   Beenden = (Gtk::MenuItem *)&Datei_menu->items().back();
   
   menubar1->items().push_back(Gtk::Menu_Helpers::MenuElem("Datei", *Datei_menu));
   Datei = (Gtk::MenuItem *)&menubar1->items().back();
   
   menubar1->items().push_back(Gtk::Menu_Helpers::MenuElem("Neuordnen"));
   neuordnen = (Gtk::MenuItem *)&menubar1->items().back();
   vbox1->pack_start(*menubar1, Gtk::PACK_SHRINK, 0);
   vbox1->pack_start(*treebase);
   window1->set_title("window1");
   window1->set_modal(false);
   window1->property_window_position().set_value(Gtk::WIN_POS_NONE);
   window1->set_resizable(true);
   window1->property_destroy_with_parent().set_value(false);
   window1->add(*vbox1);
   Beenden->show();
   Datei_menu->show();
   Datei->show();
   neuordnen->show();
   menubar1->show();
   treebase->show();
   vbox1->show();
   window1->show();
   Beenden->signal_activate().connect(SigC::slot(*this, &window1_glade::on_Beenden_activate), false);
   neuordnen->signal_activate().connect(SigC::slot(*this, &window1_glade::on_neuordnen_activate), false);
}

window1_glade::~window1_glade()
{  delete treebase;
   delete gmm_data;
}
