// generated 2010/11/15 10:25:21 CET by christof@christof-hp.(none)
// using glademm V2.13.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- --noaccelerators widgets.glade
// for gtk 2.22.0 and gtkmm 2.20.3
//
// Please modify the corresponding derived classes in ./src/datewin_popup.hh and./src/datewin_popup.cc

#ifndef _DATEWIN_POPUP_GLADE_HH
#  define _DATEWIN_POPUP_GLADE_HH

#include <gtkmm/window.h>
#include <gtkmm/calendar.h>

class datewin_popup_glade : public Gtk::Window
{  
protected:
        
        class Gtk::Calendar * calendar1;
        
        datewin_popup_glade();
        
        ~datewin_popup_glade();
private:
        virtual void datum_clicked() = 0;
        virtual void woche_clicked() = 0;
        virtual void empty_clicked() = 0;
        virtual void on_day_selected() = 0;
};
#endif
