// generated 2005/12/19 18:18:37 CET by christof@vesta.petig-baender.de
// using glademm V2.10.0.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- --noaccelerators Komponenten.glade
// for gtk 2.8.9 and gtkmm 2.8.2
//
// Please modify the corresponding derived classes in ././datewin_popup.hh and././datewin_popup.cc

#ifndef _DATEWIN_POPUP_GLADE_HH
#  define _DATEWIN_POPUP_GLADE_HH

#include <gtkmm/window.h>
#include <gtkmm/calendar.h>

class datewin_popup_glade : public Gtk::Window
{  
protected:
        
        class Gtk::Calendar * calendar1;
        
        datewin_popup_glade();
        
        ~datewin_popup_glade();
private:
        virtual void datum_clicked() = 0;
        virtual void woche_clicked() = 0;
        virtual void empty_clicked() = 0;
        virtual void on_day_selected() = 0;
};
#endif
