// generated 2006/8/14 17:36:02 CEST by christof@vesta.petig-baender.de
// using glademm V2.12.1
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- --noaccelerators Komponenten.glade
// for gtk 2.10.1 and gtkmm 2.9.10
//
// Please modify the corresponding derived classes in ././IntStringBox.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
/*
 * Standard gettext macros.
 */
#ifdef ENABLE_NLS
#  include <libintl.h>
#  undef _
#  define _(String) dgettext (GETTEXT_PACKAGE, String)
#  ifdef gettext_noop
#    define N_(String) gettext_noop (String)
#  else
#    define N_(String) (String)
#  endif
#endif
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/bind.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "IntStringBox_glade.hh"
#include <gtkmm/button.h>
#ifndef ENABLE_NLS
#  define textdomain(String) (String)
#  define gettext(String) (String)
#  define dgettext(Domain,Message) (Message)
#  define dcgettext(Domain,Message,Type) (Message)
#  define bindtextdomain(Domain,Directory) (Domain)
#  define _(String) (String)
#  define N_(String) (String)
#endif


IntStringBox_glade::IntStringBox_glade(
)
{  
   
   Gtk::EventBox *IntStringBox = this;
   label_int = Gtk::manage(new class Gtk::Label(_("Int")));
   label_string1 = Gtk::manage(new class Gtk::Label(_("Name1")));
   label_string2 = Gtk::manage(new class Gtk::Label(_("Name2")));
   sc1_string = new class SearchCombo();
   sc2_string = new class SearchCombo();
   
   Gtk::Button *button3 = Gtk::manage(new class Gtk::Button(_("leeren")));
   sc_int = new class SearchCombo();
   table = Gtk::manage(new class Gtk::Table(2, 2, false));
   label_int->set_alignment(0,0.5);
   label_int->set_justify(Gtk::JUSTIFY_CENTER);
   label_string1->set_alignment(0,0.5);
   label_string1->set_justify(Gtk::JUSTIFY_CENTER);
   label_string2->set_alignment(0,0.5);
   label_string2->set_justify(Gtk::JUSTIFY_CENTER);
   button3->set_flags(Gtk::CAN_FOCUS);
   table->attach(*label_int, 1, 2, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table->attach(*label_string1, 2, 3, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table->attach(*label_string2, 3, 4, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table->attach(*sc1_string, 2, 3, 1, 2, Gtk::EXPAND|Gtk::SHRINK|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table->attach(*sc2_string, 3, 4, 1, 2, Gtk::EXPAND|Gtk::SHRINK|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table->attach(*button3, 0, 1, 1, 2, Gtk::AttachOptions(), Gtk::AttachOptions(), 0, 0);
   table->attach(*sc_int, 1, 2, 1, 2, Gtk::SHRINK|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   IntStringBox->property_visible_window().set_value(false);
   IntStringBox->add(*table);
   label_int->show();
   label_string1->show();
   label_string2->show();
   sc1_string->show();
   sc2_string->show();
   button3->show();
   sc_int->show();
   table->show();
   IntStringBox->show();
   sc1_string->signal_activate().connect(sigc::mem_fun(*this, &IntStringBox_glade::string1_activate));
   sc1_string->signal_search().connect(sigc::mem_fun(*this, &IntStringBox_glade::string1_search), false);
   sc2_string->signal_activate().connect(sigc::mem_fun(*this, &IntStringBox_glade::string2_activate));
   sc2_string->signal_search().connect(sigc::mem_fun(*this, &IntStringBox_glade::string2_search), false);
   button3->signal_clicked().connect(sigc::mem_fun(*this, &IntStringBox_glade::reset), false);
   sc_int->signal_activate().connect(sigc::mem_fun(*this, &IntStringBox_glade::int_activate));
   sc_int->signal_search().connect(sigc::mem_fun(*this, &IntStringBox_glade::int_search), false);
   table->signal_button_press_event().connect(sigc::mem_fun(*this, &IntStringBox_glade::MouseButton), false);
}

IntStringBox_glade::~IntStringBox_glade()
{  delete sc1_string;
   delete sc2_string;
   delete sc_int;
}
