// generated 2005/12/19 18:18:37 CET by christof@vesta.petig-baender.de
// using glademm V2.10.0.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- --noaccelerators Komponenten.glade
// for gtk 2.8.9 and gtkmm 2.8.2
//
// Please modify the corresponding derived classes in ././IntStringPopup.hh and././IntStringPopup.cc

#ifndef _INTSTRINGPOPUP_GLADE_HH
#  define _INTSTRINGPOPUP_GLADE_HH

#include <gtkmm/menu.h>
#include <gtkmm/menuitem.h>

class IntStringPopup_glade : public Gtk::Menu
{  
protected:
        
        class Gtk::MenuItem * zurueck;
        
        IntStringPopup_glade();
        
        ~IntStringPopup_glade();
};
#endif
