// generated 2010/11/15 10:25:21 CET by christof@christof-hp.(none)
// using glademm V2.13.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- --noaccelerators widgets.glade
// for gtk 2.22.0 and gtkmm 2.20.3
//
// Please modify the corresponding derived classes in ./src/IntStringPopup.hh and./src/IntStringPopup.cc

#ifndef _INTSTRINGPOPUP_GLADE_HH
#  define _INTSTRINGPOPUP_GLADE_HH

#include <gtkmm/menu.h>
#include <gtkmm/menuitem.h>

class IntStringPopup_glade : public Gtk::Menu
{  
protected:
        
        class Gtk::MenuItem * zurueck;
        
        IntStringPopup_glade();
        
        ~IntStringPopup_glade();
};
#endif
