// generated 2004/9/13 10:59:20 CEST by christof@puck.petig-baender.de
// using glademm V2.6.0_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- --noaccelerators Komponenten.glade
// for gtk 2.4.9 and gtkmm 2.4.5
//
// Please modify the corresponding derived classes in ././IntStringBox.hh and././IntStringBox.cc

#ifndef _INTSTRINGBOX_GLADE_HH
#  define _INTSTRINGBOX_GLADE_HH

#include <gtkmm/eventbox.h>
#include <gtkmm/label.h>
#include "SearchCombo.hh"

class IntStringBox_glade : public Gtk::EventBox
{  
protected:
        
        class Gtk::Label * label_int;
        class Gtk::Label * label_string1;
        class Gtk::Label * label_string2;
        class SearchCombo * sc_int;
        class SearchCombo * sc1_string;
        class SearchCombo * sc2_string;
        
        IntStringBox_glade();
        
        ~IntStringBox_glade();
private:
        virtual void int_activate() = 0;
        virtual void int_search(gboolean *cont,GtkSCContext context) = 0;
        virtual void string1_activate() = 0;
        virtual void string1_search(gboolean *cont,GtkSCContext context) = 0;
        virtual void string2_activate() = 0;
        virtual void string2_search(gboolean *cont,GtkSCContext context) = 0;
        virtual void reset() = 0;
        virtual bool MouseButton(GdkEventButton *ev) = 0;
};
#endif
