// generated 2010/11/15 10:27:22 CET by christof@christof-hp.(none)
// using glademm V2.13.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- --noaccelerators widgets.glade
// for gtk 2.22.0 and gtkmm 2.20.3
//
// Please modify the corresponding derived classes in ./src/IntStringBox.hh and./src/IntStringBox.cc

#ifndef _INTSTRINGBOX_GLADE_HH
#  define _INTSTRINGBOX_GLADE_HH

#include <gtkmm/eventbox.h>
#include <gtkmm/label.h>
#include "SearchCombo.hh"
#include <gtkmm/table.h>

class IntStringBox_glade : public Gtk::EventBox
{  
protected:
        
        class Gtk::Label * label_int;
        class Gtk::Label * label_string1;
        class Gtk::Label * label_string2;
        class SearchCombo * sc1_string;
        class SearchCombo * sc2_string;
        class SearchCombo * sc_int;
        class Gtk::Table * table;
        
        IntStringBox_glade();
        
        ~IntStringBox_glade();
private:
        virtual void string1_activate() = 0;
        virtual void string1_search(gboolean *cont,GtkSCContext context) = 0;
        virtual void string2_activate() = 0;
        virtual void string2_search(gboolean *cont,GtkSCContext context) = 0;
        virtual void reset() = 0;
        virtual void int_activate() = 0;
        virtual void int_search(gboolean *cont,GtkSCContext context) = 0;
        virtual bool MouseButton(GdkEventButton *ev) = 0;
};
#endif
