// generated 2004/9/13 10:59:20 CEST by christof@puck.petig-baender.de
// using glademm V2.6.0_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- --noaccelerators Komponenten.glade
// for gtk 2.4.9 and gtkmm 2.4.5
//
// Please modify the corresponding derived classes in ././IntStringPopup.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "IntStringPopup_glade.hh"

IntStringPopup_glade::IntStringPopup_glade(
)
{  
   
   Gtk::Menu *IntStringPopup = this;
   zurueck = NULL;
   
   IntStringPopup->items().push_back(Gtk::Menu_Helpers::MenuElem("Zurücksetzen"));
   zurueck = (Gtk::MenuItem *)&IntStringPopup->items().back();
   zurueck->show();
   IntStringPopup->show();
}

IntStringPopup_glade::~IntStringPopup_glade()
{  
}
