// generated 2004/9/13 10:59:20 CEST by christof@puck.petig-baender.de
// using glademm V2.6.0_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- --noaccelerators Komponenten.glade
// for gtk 2.4.9 and gtkmm 2.4.5
//
// Please modify the corresponding derived classes in ././IntStringPopup.hh and././IntStringPopup.cc

#ifndef _INTSTRINGPOPUP_GLADE_HH
#  define _INTSTRINGPOPUP_GLADE_HH

#include <gtkmm/menu.h>
#include <gtkmm/menuitem.h>

class IntStringPopup_glade : public Gtk::Menu
{  
protected:
        
        class Gtk::MenuItem * zurueck;
        
        IntStringPopup_glade();
        
        ~IntStringPopup_glade();
};
#endif
