// generated 2006/3/9 22:41:55 CET by christof@vesta.petig-baender.de
// using glademm V2.12.1
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- --noaccelerators Komponenten.glade
// for gtk 2.8.13 and gtkmm 2.8.3
//
// Please modify the corresponding derived classes in ././IntStringBox.hh and././IntStringBox.cc

#ifndef _INTSTRINGBOX_GLADE_HH
#  define _INTSTRINGBOX_GLADE_HH

#include <gtkmm/eventbox.h>
#include <gtkmm/label.h>
#include "SearchCombo.hh"
#include <gtkmm/table.h>

class IntStringBox_glade : public Gtk::EventBox
{  
protected:
        
        class Gtk::Label * label_int;
        class Gtk::Label * label_string1;
        class Gtk::Label * label_string2;
        class SearchCombo * sc1_string;
        class SearchCombo * sc2_string;
        class SearchCombo * sc_int;
        class Gtk::Table * table;
        
        IntStringBox_glade();
        
        ~IntStringBox_glade();
private:
        virtual void string1_activate() = 0;
        virtual void string1_search(gboolean *cont,GtkSCContext context) = 0;
        virtual void string2_activate() = 0;
        virtual void string2_search(gboolean *cont,GtkSCContext context) = 0;
        virtual void reset() = 0;
        virtual void int_activate() = 0;
        virtual void int_search(gboolean *cont,GtkSCContext context) = 0;
        virtual bool MouseButton(GdkEventButton *ev) = 0;
};
#endif
